name: CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@v4

    - name: Stop Gunicorn server and screen session
      run: |
        # Send SIGTERM to all processes in the screen session
        sudo screen -S finance -X stuff $'\003'  # Ctrl+C
        sleep 5  # Wait for processes to terminate gracefully
        # Forcefully kill the screen session if it still exists
        sudo screen -XS finance quit || true 

    - name: Start Gunicorn server in a new screen
      run: |
        cd $GITHUB_WORKSPACE
        sudo screen -dmS finance sudo npm run dev -- --host 0.0.0.0 --port 80
        


